### ISSUE TITLE
Make clearer what snippets should and shouldn't be copied.

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guide-rest-intro#10]
By section...

## What you'll learn

* Tag both snippets with `no_copy`. Although the URL could be useful when running the app, it should instead be repeated later on when needed. At this stage in the guide, the user doesn't need to copy it - if they copy it now into a browser, they'll get an error because the app isn't running.

## Getting started

This should have the copy button, so no change required.

## Creating a JAX-RS application

* Put a colon (:) at the end of "file" before the first snippet to associate the snippet with the sentence before it which refers to the snippet.

## Creating the JAX-RS resource

* Put a colon (:) at the end of "file" before the first snippet to associate the snippet with the sentence before it which refers to the snippet.
* The first snippet (which contains the full JAX-RS resource class) should have a copy button (so no change required).
* The other two snippets should be tagged `no_copy`. They are just highlighting bits of the previous code to explain how and why it works.

## Building the application

* `mvn install` should have the copy button (no change).
* `mvn package` should have the copy button (no change).

## Testing the service

* Put a colon (:) at the end of "file" before the first snippet to associate the snippet with the sentence before it which refers to the snippet.
* The first snippet (which contains the full test class) should have a copy button (so no change required).
* The next two snippets contain XML which is already in the `pom.xml`. They should be tagged `no_copy`.
* I think the lead-ins to the XML snippets could be clearer though. Change the lead-in sentence "While this information can be hardcoded, it is better to specify it in a single place like the Maven pom.xml file:" to "While this information can be hardcoded, it is better to specify it in a single place like the Maven pom.xml file. Open the `pom.xml` file to see how the application information is provided there:"
* Similarly, change "These Maven properties can then be passed to the Java test program as a series of system properties:" to "These Maven properties are then passed to the Java test program as a series of system properties in the `pom.xml`:"
* The fourth snippet in that section contains Java from the test class:
  * Tag the snippet `no_copy`.
  * Change "Getting the values to then create a representation of the URL is then simple:" to "Getting the values to then create a representation of the URL is simple. The test class just uses the properties to get the application details:".
* Snippets 5-8 should also be tagged with `no_copy` as they, again, just highlight and explain what's happening in the first snippet.
* Snippet 9 is part of the instruction to update the `server.xml` file:
  * It should have the copy button (no change required).
  * However, for clarity, change: "Update the src/main/liberty/config/server.xml file:" to "Update the src/main/liberty/config/server.xml file by replacing the placeholder text with the following XML code:"
* Snippet 10 is just illustrating what's in the `pom.xml` file so tag this as `no_copy`.
* The last snippet is just console output so should be tagged `no_copy` (it already is, so no change required).

**Comment by yeekangc** [comment]
@sishida, will you be able to take a look at this?

**Comment by sishida** [comment]
Link to the pull request I made for these changes: https://github.com/OpenLiberty/guide-rest-intro/pull/11

**Comment by sishida** [comment]
@yeekangc and @lauracowen: Hi, team, Is this defect good to close? If not, could you please let me know how I can continue working on it? Thank you!

**Comment by Kubik42** [comment]
@yeekangc I think this is safe to close?

**Comment by yeekangc** [comment]
Yes!
