### ISSUE TITLE
Automation is not testing the daily build properly

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guide-rest-intro#103]
Check the travis log: https://travis-ci.org/OpenLiberty/guide-rest-intro/builds/611302298

2 issues: 
- [x] The test is running `mvn clean install` instead of `travisTest.sh` script
- [x] The daily build `runtimeURL` is not being specified in the pom.xml for the daily build runs

**Comment by evelinec** [comment]
@gkwan-ibm @NimG98

**Comment by NimG98** [comment]
It's running mvn clean install, and not the travisTest.sh

Will update the daily build script

**Comment by evelinec** [comment]
The getting-started travisTest.sh script has its own issue as well, see https://github.com/OpenLiberty/guide-getting-started/issues/130.

**Comment by evelinec** [comment]
There's another issue for running the daily build in general, that is, the build needs to be replaced with the daily build via the `runtimeURL` element. This hasn't been done for the dec mode converted guides. @NimG98

**Comment by gkwan-ibm** [comment]
https://travis-ci.org/OpenLiberty/guide-rest-intro/builds/614997796 can show that the issue was fixed
