### ISSUE TITLE
Add the installation of WebSphere as a requisite

### ISSUE THREAD

**Issue by Diego448** [OpenLiberty/guide-rest-intro#135]
As long as I can see the requsites for this guide only mentions git, Java and Maven, but never mentions to install the WebSphere server. I know experienced developers should infer that, but newcomers will not, so might be useful to add that requisite and maybe point a url to a guide for the installation.

**Comment by yeekangc** [comment]
Thank you for the feedback, @Diego448.  Then, WebSphere is not required for the Open Liberty guides.  And, Open Liberty will be pulled down automatically by the build plugins e.g. Liberty Maven Plugin if you are using Maven.

Can you please elaborate and clarify your issue with WebSphere?

**Comment by Diego448** [comment]
Sorry about that, after posting this I noticed you are using an embedded server inside the repo, I will just close this Issue, since is no longer required. Thanks for the early response

**Comment by yeekangc** [comment]
No problem and thank you, @Diego448.
