### ISSUE TITLE
When I generate a rest service using gradle, when accessing the resource I get the error: Error 404: java.io.FileNotFoundException: SRVE0190E: File not found: /api/customers

### ISSUE THREAD

**Issue by mssalazarb** [OpenLiberty/guide-rest-intro#141]
gradle.build
![image](https://user-images.githubusercontent.com/55903640/93239341-437a0e80-f748-11ea-9e44-b092ad825992.png)

server.xml
![image](https://user-images.githubusercontent.com/55903640/93239386-5260c100-f748-11ea-9b24-d2eaa4cc9feb.png)

Application class
![image](https://user-images.githubusercontent.com/55903640/93239460-6c020880-f748-11ea-9955-75d86f3b8ff5.png)

RestService class
![image](https://user-images.githubusercontent.com/55903640/93239497-7b815180-f748-11ea-83ce-346a650a651f.png)

**Comment by AustinSeto** [comment]
Hi there!

I tried to recreate this error, but was unable to do so. I used the task `libertyDev` with the described `gradle.build` and made modifications to the existing code in the `finish` directory of the guide to match what was shown. 

What is the full URL you are visiting? Is it `http://localhost:9080/api/customers` or `http://localhost:9080/servidor1/api/customers`?

**Comment by slominskir** [comment]
I'm running into this issue too (while attempting to port working Maven demo to Gradle), but discovered that logging config is hiding boot issues from the console (at least using IntelliJ with Liberty plugin). 

I stumbled on the log file at `build\wlp\usr\servers\defaultServer\logs\messages.log` and it includes lines like:

```
 com.ibm.ws.injectionengine.InjectionProcessorManager         W CWNEN0047W: Resource annotations on the fields of the com.example.Demo class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: Ljavax/ws/rs/sse/Sse;
```

Clearly dependencies aren't included properly (specifically JAX-RS 2.1).   There is a lot of layers of "magic" going on so it is hard to trace what I've got configured wrong.

**Comment by AustinSeto** [comment]
Hi @slominskir I am unable to recreate the error you described. What are the `build.gradle` and `settings.gradle` files you are using? 

I ran using the files in the `finish` directory and using the following Gradle files using `gradle libertyDev` and ran into no issues. My log files do not have any error like the one you describe. 

**build.gradle**
```
apply plugin: 'war'
apply plugin: 'liberty'

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'io.openliberty.tools:liberty-gradle-plugin:3.0'
    }
}

repositories {
    mavenCentral()
}

dependencies {
    providedCompile 'jakarta.platform:jakarta.jakartaee-api:8.0.0'
    providedCompile 'org.eclipse.microprofile:microprofile:4.0.1'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.7.1'
    testImplementation 'commons-httpclient:commons-httpclient:3.1'
}

ext  {
    liberty.server.var.'default.http.port' = '9080'
    liberty.server.var.'default.https.port' = '9443'
    liberty.server.var.'app.context.root' = project.name
}
```

**settings.gradle**
```
rootProject.name = 'LibertyProject'
```

If you use these `.gradle` files, do you still experience the error?

**Comment by gkwan-ibm** [comment]
hi @mssalazarb 

Based on your description, the `/api/customers` is not a valid REST api path, unless there is a method with `@GET` in the CustomerRest class. The description does not show the full content of the CustomerRest class, so we cannot conclude why you got 404. Would you share to us the full content of the CustomerRest class?

**Comment by gkwan-ibm** [comment]
hi @slominskir 

I guess your problem is not from the application of this guide. From your log, you created `com.example.Demo` class. Right? Would you share to us the full content of the Demo class? If ok, as well as your server.xml and build.gradle files.

**Comment by slominskir** [comment]
I'm attempting to create an Open Liberty project that uses Gradle, Kafka, and SSE.   I start with the example here:   https://github.com/openliberty/guide-reactive-messaging-sse.git.  This example sometimes works as is, sometimes doesn't work because web browser fails to connect to bff service due to CORS issue.   Sometimes waiting for all containers to come up fixes it, sometimes restarting a bunch of times fixes it.  Whole thing feels very fragile to begin with.

I was trying to start from scratch, but now I stuck with CORS issue again.   Hmmm...

**Comment by gkwan-ibm** [comment]
hi @slominskir

Look like your issue now does not relate to this guide. Regarding the reactive-messaging-sse guide, it should be a timing issue. We'll see anything that can improve the application. 

If you still need a support for [your issue](https://github.com/OpenLiberty/guide-rest-intro/issues/141#issuecomment-879339007) posted in above, would you provide us more information?

If you have any question about the Open Liberty, you may visit https://openliberty.io/support. At the Community support section, you may select your favor channel to get support.

**Comment by gkwan-ibm** [comment]
close
- see above comments
