### ISSUE TITLE
Project code does not work

### ISSUE THREAD

**Issue by mmswenson** [OpenLiberty/guide-rest-intro#206]
Error 404: com.ibm.ws.webcontainer.servlet.exception.NoTargetForURIException: No target servlet configured for uri: /LibertyProject/system/properties

**Comment by gkwan-ibm** [comment]
hi @mmswenson 

Thanks to report your problem to us. 

If there is another application running with the same port 9080, this problem may happen. Would you make sure there is no other application is running with the same port? Otherwise, would you give us more information so that we can investigate?
- the Maven setting by running `mvn -version`
- in which section of the guide you encountered the problem?

**Comment by mmswenson** [comment]
Yes there was,  I found and disabled the application using that port.

From: Gilbert Kwan ***@***.***>
Sent: Wednesday, March 29, 2023 8:40 AM
To: OpenLiberty/guide-rest-intro ***@***.***>
Cc: Michael Swenson ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [OpenLiberty/guide-rest-intro] Project code does not work (Issue #206)

hi @mmswenson Thanks to report your problem to us. If there is another application running with the same port 9080, this problem may happen. Would you make sure there is no other application is running with the same port? Otherwise, would you
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

hi @mmswenson<https://github.com/mmswenson>

Thanks to report your problem to us.

If there is another application running with the same port 9080, this problem may happen. Would you make sure there is no other application is running with the same port? Otherwise, would you give us more information so that we can investigate?

  *   the Maven setting by running mvn -version
  *   in which section of the guide you encountered the problem?

-

**Comment by gkwan-ibm** [comment]
hi @mmswenson

After disabled the application using that port, did you still encounter the problem?

Or are you reporting that the /LibertyProject/system/properties does not work if there is another application running with the same port?

**Comment by mmswenson** [comment]
I was able to get it working, thanks.
________________________________
From: Gilbert Kwan ***@***.***>
Sent: Wednesday, March 29, 2023 10:37 AM
To: OpenLiberty/guide-rest-intro ***@***.***>
Cc: Michael Swenson ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [OpenLiberty/guide-rest-intro] Project code does not work (Issue #206)

hi @mmswenson After disabled the application using that port, did you still encounter the problem? Or are you reporting that the /LibertyProject/system/properties does not work if there is another application running with the same port? —Reply
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.

ZjQcmQRYFpfptBannerEnd

hi @mmswenson<https://github.com/mmswenson>

After disabled the application using that port, did you still encounter the problem?

Or are you reporting that the /LibertyProject/system/properties does not work if there is another application running with the same port?

**Comment by gkwan-ibm** [comment]
close
- the problem was resolved
