### ISSUE TITLE
There is no mvn 

### ISSUE THREAD

**Issue by Oanh-D** [OpenLiberty/guide-rest-intro#214]
got error bash: mvn: command not found

**Comment by gkwan-ibm** [comment]
hi @Oanh-D 

JDK, Git, and  Maven are the prerequisites to run this guide. You can install them through the following 3 buttons that are located on the right top of the guide. Or, you can try the guide in a hosted environment, without having to worry about local setup and prerequisites, by clicking the `Run in cloud` button.

![Screenshot 2024-01-09 at 10 37 13 AM](https://github.com/OpenLiberty/guide-rest-intro/assets/29576299/2c4401e3-7810-46ba-a505-20e5d05cf326)

**Comment by gkwan-ibm** [comment]
close
- welcome to reopen or create a new issue if the above [comment](https://github.com/OpenLiberty/guide-rest-intro/issues/214#issuecomment-1883300576) cannot answer the issue
