### ISSUE TITLE
How to create uber-jar for rest-intro guide

### ISSUE THREAD

**Issue by surajchhetry** [OpenLiberty/guide-rest-intro#22]
How to create uber jar so that we can deploy it on heruko ?

**Comment by yeekangc** [comment]
Hi @surajchhetry.  Can you please elaborate on your question?

When you said uber jar, what sort of uber jar were you referring to?

Are you wanting to deploy onto Liberty in Heroku?

Also, this probably isn't the right forum for such question.  You can re-post to https://groups.io/g/openliberty.

Thank you.

**Comment by gkwan-ibm** [comment]
hi @surajchhetry,

I am going to close this issue. You may reopen and provide more information to us if you still consider it is an issue for this guide?

Thanks
