### ISSUE TITLE
Instruction flow is confusing in the Test section

### ISSUE THREAD

**Issue by barecode** [OpenLiberty/guide-rest-intro#23]
In the **Testing the service** step, the guide states
"You could test this service manually by starting a server and pointing a web browser at the http://localhost:9080/LibertyProject/System/properties URL. "

However, at this point the application is _not_ deployed because the server.xml is intentionally empty.

This resulted in confusion for myself and others at Index 2018.

Consider the following remedies:
1. Reword the sentence to not imply the URL is available.
2. Or better yet, re-order the guide so that when the server is first started, the application is actually available and ready for use. As a user, when I start the server, I expect the application I just wrote to be available. The current ordering is confusing and unexpected.

Thanks,
Mike

**Comment by yeekangc** [comment]
@JunyiSun, can you please double check if anymore work needs to be done for this?  If not, we can close.

**Comment by JunyiSun** [comment]
@yeekangc it's fixed already by #25
