### ISSUE TITLE
Currently JAVA_HOME is not set

### ISSUE THREAD

**Issue by dougbreaux** [OpenLiberty/guide-rest-intro#255]

**Comment by gkwan-ibm** [comment]
hi @dougbreaux 

would you clarify more? Do you mean that "JAVA_HOME is not set in the **Run in cloud** or **Skill network lab** environment when you ran mvn command"?

If it is the case, the problem was resolved.

**Comment by dougbreaux** [comment]
Yes, that's what I meant. I opened this Issue from that environment, so I assume it would provide the necessary context 😄

**Comment by gkwan-ibm** [comment]
close
- the issue in SN lab was resolved
