### ISSUE TITLE
Rest Intro guide comments in external issue...

### ISSUE THREAD

**Issue by kwsutter** [OpenLiberty/guide-rest-intro#28]
Just raising your awareness to https://github.com/OpenLiberty/open-liberty/issues/2644.  @hutchig accidentally created this in the top-level Open Liberty repo instead of the repo specific to the guide...  And, I don't know of an easy way to move an Issue from one repo to the next.  I want to make sure that you caught this before our cut-off for Think.  Thanks!

**Comment by JunyiSun** [comment]
@kwsutter Thanks for letting us know, it is fixed in PR #29

**Comment by hutchig** [comment]
PR Approved.
