### ISSUE TITLE
The Maven sections in your guides mismatch the paragraphs around it

### ISSUE THREAD

**Issue by heindrichpaul** [OpenLiberty/guide-rest-intro#46]
The two sections that are incorrect are copied below:

It states the following:

The variables being used in the server.xml file are provided by the bootstrapProperties section of the Maven ```pom.xml```:
```
            </excludes>
            <reportsDirectory>${project.build.directory}/test-reports/unit</reportsDirectory>
        </configuration>
    </execution>
</executions>
```
But it should be something like:

```
                    <bootstrapProperties>
                        <default.http.port>${testServerHttpPort}</default.http.port>
                        <default.https.port>${testServerHttpsPort}</default.https.port>
                        <app.context.root>${warContext}</app.context.root>
                    </bootstrapProperties>
```

The second error is stating the following:

These Maven properties are then passed to the Java test program as a series of system properties in the ```pom.xml``` file:

 ```           <outputDirectory>target/wlp-package</outputDirectory>
        </configuration>
    </execution>
</executions>
```

and it should be:

```
                            <systemPropertyVariables>
                                <liberty.test.port>${testServerHttpPort}</liberty.test.port>
                                <war.name>${warContext}</war.name>
                            </systemPropertyVariables>
```

**Comment by andrewdes** [comment]
@heindrichpaul thanks for pointing this out. This issue has been fixed here: https://github.com/OpenLiberty/guide-rest-intro/commit/389904a64df2590685028aa769468cc77e320d8b and the changes can be seen on the Open Liberty website: https://openliberty.io/guides/rest-intro.html . Can this issue be closed?
