### ISSUE TITLE
Java EE 8 update to app needed?

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guide-rest-intro#55]
Does this guide app need updating? There's a comment in it "This gap in the specification is fixed in Java EE 8 with the inclusion of JSON-B." that's obviously been added in later but it's not clear why. What's that comment saying?

Is it saying that the guide uses the old method but it's possible to do it with the new method? If so, can we update the app so that it uses the new method?

Or is it saying that we've updated it to the new method? (in which case, I think this needs rewording and possibly removing mention of Java EE 8 - although it's cool and up-to-date, it will become dated. The same goes for the note about 'new in Java SE 8'. We should probably just focus on making sure the tech is up-to-date and not tie the guides to a specific point in time.)

**Comment by justineechen** [comment]
After discussion with @andymc12, he explained that the line is still relevant but not necessary to the guide so I have created a PR to remove the two mentions that tie the guides to a specific point in time.
