### ISSUE TITLE
Failure running mvn install

### ISSUE THREAD

**Issue by azusaaz** [OpenLiberty/guide-rest-intro#60]
-------------------------------------------------------
 T E S T S
-------------------------------------------------------

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.242 s
[INFO] Finished at: 2019-02-05T20:11:28-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.18.1:integration-test (integration-test) on project rest: Execution integration-test of goal org.apache.maven.plugins:maven-failsafe-plugin:2.18.1:integration-test failed: There was an error in the forked process
[ERROR] java.lang.RuntimeException: Unable to create test class 'it.io.openliberty.guides.rest..gitkeep'
[ERROR] 	at org.apache.maven.surefire.util.DefaultScanResult.loadClass(DefaultScanResult.java:135)
[ERROR] 	at org.apache.maven.surefire.util.DefaultScanResult.applyFilter(DefaultScanResult.java:95)
[ERROR] 	at org.apache.maven.surefire.junit4.JUnit4Provider.scanClassPath(JUnit4Provider.java:222)
[ERROR] 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:107)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
[ERROR] Caused by: java.lang.ClassNotFoundException: it.io.openliberty.guides.rest..gitkeep
[ERROR] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
[ERROR] 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
[ERROR] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[ERROR] 	at org.apache.maven.surefire.util.DefaultScanResult.loadClass(DefaultScanResult.java:131)
[ERROR] 	... 6 more
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by yeekangc** [comment]
@azusaaz was working with Maven 2.6.0 and Java 11 on Mac.

**Comment by azusaaz** [comment]
I started over again, but I got the same errors.
I updated the way to set JAVA_HOME, but the result was the same.
It may be occurred my local settings, or I may have missed something.

MacOS 10.13.6 (High Sierra)
Maven 3.6.0
JDK 11.0.2

$ git clone https://github.com/openliberty/guide-rest-intro.git
$ cd guide-rest-intro
create: src/main/java/io/openliberty/guides/rest/SystemApplication.java
create: src/main/java/io/openliberty/guides/rest/PropertiesResource.java 
update: src/main/liberty/config/server.xml
$ cd start
~$ export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.11.0.2.jdk/Contents/Home~
$ vim .bash_profile 
write: export JAVA_HOME=$(/usr/libexec/java_home)
$ source .bash_profile
$ export PATH=/opt/apache-maven-3.6.0/bin:$PATH
$ mvn install    -> error happened



current setting:
$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk-11.0.2.jdk/Contents/Home
$ echo $PATH
/opt/apache-maven-3.6.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

**Comment by yeekangc** [comment]
Thank you for the update, @azusaaz.  We are looking into it.

**Comment by yeekangc** [comment]
@gkwan-ibm @andrewdes @justineechen

**Comment by gkwan-ibm** [comment]
@azusaaz  We will fix this issue in near future. At this moment, would you try the following in the start/pom.xml?
- locate
```
    <artifactId>maven-failsafe-plugin</artifactId>
    <version>2.18.1</version>
```
- change 2.18.1 to 3.0.0-M1
 - locate
```
    <artifactId>maven-surefire-plugin</artifactId>
    <version>2.18.1</version>
```
- change 2.18.1 to 3.0.0-M1
- save the pom.xml
- run the command `mvn install` again

**Comment by azusaaz** [comment]
@gkwan-ibm Sure! Just a moment please.

**Comment by azusaaz** [comment]
@gkwan-ibm  build success!  Thank you so much!
