### ISSUE TITLE
Multipane - Post publish test

### ISSUE THREAD

**Issue by andrewdes** [OpenLiberty/guide-rest-intro#64]
- [x] Check appearance (contents, headings, paragraphs, code snippets, outputs, links, hotspots) of the guide
- [x] Read through the guide 
- [x] Clone repo and test finish directory with no error
- [x] Run `diff -r start/ finish/` 
- [x] Follow the instruction in the guide to test that it is working
- [x] Use the `copy` buttons instead of typing 
- [x] Links open in new tab
- [x] Hotspots highlight the correct code
- [x] Action arrows do not highlight any code
- [x] Update action arrows have hotspotted text underneath
- [x] Full files mentioned in the guide as hotspots should not highlight any code
- [x] Hovering over code commands should switch to the right file

**Comment by andrewdes** [comment]
- [ ] "If the server is still running from the previous steps, stop it using the Maven liberty:stop-server goal from command line in the start directory:" -> `liberty:stop-server` should be in backticks

**Comment by gkwan-ibm** [comment]
fixed by PR #66
